version: '3'
services:
  laravel_app:
    container_name: site_willgarrett_laravel
    build:
      context: php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: site
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - maria_db
    volumes:
      - ./src:/var/www
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - local
    environment:
      - DB_HOST=maria_db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
  node:
    image: node:8
    container_name: site_willgarrett_node
    volumes:
      - ./src:/var/www
    networks:
      - local
  nginx:
    image: nginx:alpine
    container_name: site_willgarrett_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "4430:443"
    networks:
      - local
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./src:/var/www
      - ${HOST_DATA_PATH}/nginx:/var/log/nginx
    depends_on:
      - laravel_app
  selenium:
    container_name: site_willgarrett_selenium-standalone-debug
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "59000:5900" ## VNC default password is "secret"
    networks:
      - local
  maria_db:
    container_name: site_willgarrett_maria_db
    build: ./mariadb
    volumes:
      - ${HOST_DATA_PATH}/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DB}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASS}
    networks:
      - local
  redis:
    container_name: site_willgarrett_redis
    image: redis:alpine
    volumes:
     - ${HOST_DATA_PATH}/redis:/data
    networks:
      - local
networks:
  local:
    driver: bridge